import Head from "next/head";
import "./globals.css";
// import { Ubuntu } from 'next/font/google'

// const ubuntu = Ubuntu({ subsets: ['latin'] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link
          href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@300;400;500;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body 
      // className={ubuntu.className}
      >{children}</body>
    </html>
  );
}
